Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -56,9 +56,23 @@ phases:
 
       # 2. ĐĂNG NHẬP DOCKER HUB (Sử dụng Secrets Manager)
       - |
-        echo "DEBUG: DOCKER_CREDS_ARN value is: '${DOCKER_CREDS_ARN}'"
-        if [ -n "${DOCKER_CREDS_ARN}" ]; then DOCKER_CREDS=$(aws secretsmanager get-secret-value --secret-id "${DOCKER_CREDS_ARN}" --query SecretString --output text); DOCKER_USER=$(echo $DOCKER_CREDS | jq -r '.username'); DOCKER_PASS=$(echo $DOCKER_CREDS | jq -r '.password'); if [ -n "$DOCKER_PASS" ]; then echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin; else echo "ERROR: Failed to parse DOCKER_PASS." && exit 1; fi; else echo "FATAL ERROR: DOCKER_CREDS_ARN is EMPTY. Re-check CodeBuild UI." && exit 1; fi
-
+        echo "DEBUG: DOCKER_SECRET_ID value is: '${DOCKER_SECRET_ID}'"
+        if [ -n "${DOCKER_SECRET_ID}" ]; then
+          echo "🐳 Logging into Docker Hub to bypass pull rate limit..."
+          
+          # Lấy chuỗi JSON Secret (ARN/ID được truyền dưới dạng Plaintext)
+          DOCKER_CREDS=$(aws secretsmanager get-secret-value --secret-id "${DOCKER_SECRET_ID}" --query SecretString --output text)
+          
+        
+          echo "DEBUG: Extracted Username: ${DOCKER_USER}"
+          
+          if [ -n "$DOCKER_PASS" ]; then
+            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
+          else
+            echo "FATAL ERROR: Failed to parse DOCKER_PASS. Key JSON trong Secret KHÔNG PHẢI là 'thanhlam2k4'."
+            exit 1 
+          fi
+        fi
       # 3. XÁC THỰC VÀ ĐĂNG NHẬP DOCKER VỚI GCP ARTIFACT REGISTRY
       - |
         echo "DEBUG: GCP_SA_KEY_ARN value is: '${GCP_SA_KEY_ARN}'"
